#!/usr/bin/env groovy

// list of services
def list = [
  "service1",
  "service2",
  "service3",
  "service4",
  "service4v2",
  "service5",
  "service6",
  "service6listener",
  "service7",
  "service8",
  "service8v2",
  "service9",
  "service10"
]
pipeline {
    options {
        buildDiscarder(logRotator(daysToKeepStr: '6'))
    }
    agent any
    stages {
        stage('Preparing updated services') {
            steps {
                script {
                    // for loop to check all the services
                    for(int i=0; i < list.size(); i++) {
                        if("${list[i]}"!="service4" && "${list[i]}"!="service4v2" && "${list[i]}"!="service9" && "${list[i]}"!="service9v2" && "${list[i]}"!="service6" && "${list[i]}"!="service6listener" && "${list[i]}"!="service7" && "${list[i]}"!="service8" ){
                            matches1 = sh (
                                script: "git diff --name-only HEAD~1 | sort -u | awk -F/ {'print \$2'} | uniq | grep -x '${list[i]}'", returnStatus: true
                            ) == 0
                            echo "Matches1: $matches1 for Service: ${list[i]}" >> Matches1.property
                        }
                     
                                     // condition for version 2 services
                        else if ("${list[i]}"=="service4v2" || "${list[i]}"=="service9v2"){
                            redir1 = "${list[i]}".toString().replaceAll("v2","")
                            matches2 = sh (
                                script: "git diff --name-only HEAD~1 | sort -u | awk -F/ {'print \$2,\$3'} | uniq | grep -x '${redir1} v2'", returnStatus: true
                            ) == 0
                            echo "Matches2: $matches2 for Service: ${list[i]} " >> Matches2.property
                        }
                        
                         else if ("${list[i]}"=="service4" || "${list[i]}"=="service9") {
                            matches3 = sh (
                                script: "(git diff --name-only HEAD~1 | sort -u | awk -F/ {'print \$2,\$3'} | uniq | grep -x '${list[i]} api')", returnStatus: true
                            ) == 0
                            echo "Matches3: $matches3 for Service: ${list[i]}" >> Matches3.property
                        }

                        else if ("${list[i]}"=="service6listener") {
                            redir2 = "${list[i]}".toString().replaceAll("listener","")
                            matches4 = sh (
                                script: "git diff --name-only HEAD~1 | sort -u | awk -F/ {'print \$1,\$2'} | uniq | grep -x 'listeners ${redir2}'", returnStatus: true
                            ) == 0
                            echo "Matches4: $matches4 for Listener: ${list[i]}" >> Matches4.property
                        }


                        else if ("${list[i]}"=="service6") {
                            matches5 = sh (
                                script: "git diff --name-only HEAD~1 | sort -u | awk -F/ {'print \$1,\$2'} | uniq | grep -x 'services ${list[i]}'", returnStatus: true
                            ) == 0
                            echo "Matches5: $matches5 for Service: ${list[i]}" >> Matches5.property
                        }

                        else if ("${list[i]}"=="servive8") {
                            matches6 = sh (
                                script: "git diff --name-only HEAD~1 | sort -u | awk -F/ {'print \$3'} | uniq | grep -x '${list[i]}'", returnStatus: true
                            ) == 0
                            echo "Matches6: $matches6 for dotnet Service: ${list[i]}" >> Matches6.property
                        }


                        else if ("${list[i]}"=="service7") {
                            matches7 = sh (
                                script: "git diff --name-only HEAD~1 | sort -u | awk -F/ {'print \$2'} | uniq | grep -x '${list[i]}'", returnStatus: true
                            ) == 0
                            echo "Matches7: $matches7 for Service: ${list[i]}" >> Matches7.property
                        }

                    }
                    
                    stage('Build Microserices'){
                        
                        // failFast true   
                     parallel { 
                     
                            stage ('check condition 1'){
                                steps{
			                            sh '''	
			                             set +e
                                  grep -nr "true" ./matches1.txt
                                  if [ $? -eq 0 ] ; then
                                  grep -nr 'true' ./matches1.txt > m1run.txt
                                  while IFS= read -r line ; do
                                  DIR=$(echo $line | awk '{print $5}' )
                                  echo "$DIR"
                                  #docker build -f services/$DIR/build/Dockerfile .
                                  ls -l services/$DIR/build/
                                  done < m1run.txt
                                  else
                                  echo "not macth found"
                                  fi
                                   set -e     
                                '''	                                  
                                }
 
                               }
                               
                            stage ('check condition 2'){
                                steps{
			                            sh '''	
			                             set +e
                                  grep -nr "true" ./matches2.txt
                                  if [ $? -eq 0 ] ; then
                                  grep -nr 'true' ./matches2.txt > m2run.txt
                                  while IFS= read -r line ; do
                                  DIR=$(echo $line | awk '{print $5}' )
                                  echo "$DIR"
                                  #docker build -f services/$DIR/build/Dockerfile .
                                  ls -l services/$DIR/build/
                                  done < m2run.txt
                                  else
                                  echo "not macth found"
                                  fi
                                   set -e     
                                '''	  

                                }
 
                            }
                            
                            stage ('check condition 3'){
                                
                                steps{
			                            sh '''	
			                             set +e
                                  grep -nr "true" ./matches3.txt
                                  if [ $? -eq 0 ] ; then
                                  grep -nr 'true' ./matches3.txt > m3run.txt
                                  while IFS= read -r line ; do
                                  DIR=$(echo $line | awk '{print $5}' )
                                  echo "$DIR"
                                  #docker build -f services/$DIR/build/Dockerfile .
                                  ls -l services/$DIR/build/
                                  done < m3run.txt
                                  else
                                  echo "not macth found"
                                  fi
                                   set -e     
                                '''	  
                                }
 
                            }
                            stage ('check condition 4'){
                                
                                steps{
			                            sh '''	
			                             set +e
                                  grep -nr "true" ./matches4.txt
                                  if [ $? -eq 0 ] ; then
                                  grep -nr 'true' ./matches4.txt > m4run.txt
                                  while IFS= read -r line ; do
                                  DIR=$(echo $line | awk '{print $5}' )
                                  echo "$DIR"
                                  #docker build -f services/$DIR/build/Dockerfile .
                                  ls -l services/$DIR/build/
                                  done < m4run.txt
                                  else
                                  echo "not macth found"
                                  fi
                                   set -e     
                                '''	  
                            }  
                                }
 
                            } 
                            stage ('check condition 5'){
                                
                            steps{
			                            sh '''	
			                             set +e
                                  grep -nr "true" ./matches5.txt
                                  if [ $? -eq 0 ] ; then
                                  grep -nr 'true' ./matches5.txt > m5run.txt
                                  while IFS= read -r line ; do
                                  DIR=$(echo $line | awk '{print $5}' )
                                  echo "$DIR"
                                  #docker build -f services/$DIR/build/Dockerfile .
                                  ls -l services/$DIR/build/
                                  done < m5run.txt
                                  else
                                  echo "not macth found"
                                  fi
                                   set -e     
                                '''	  
                                }
                                
                            }  
                            stage ('check condition 6'){
                                
                                steps{
                                  
                                   sh '''	
			                             set +e
                                  grep -nr "true" ./matches6.txt
                                  if [ $? -eq 0 ] ; then
                                  grep -nr 'true' ./matches6.txt > m6run.txt
                                  while IFS= read -r line ; do
                                  DIR=$(echo $line | awk '{print $5}' )
                                  echo "$DIR" 
                                  cd dotnet/services/$DIR && dotnet clean && dotnet build && cd -
                                  cd dotnet/tests/CalculatedDepthSeriesTests && dotnet test --no-restore && cd -
                                  #docker build -f services/$DIR/build/Dockerfile .
                                  ls -l services/$DIR/build/
                                  done < m6run.txt
                                  else
                                  echo "not macth found"
                                  fi
                                   set -e     
                                '''	  
                                  
                                }
 
                            } 
                            stage ('check condition 7'){
                                
                                steps{
                                  	sh '''	
			                             set +e
                                  grep -nr "true" ./matches7.txt
                                  if [ $? -eq 0 ] ; then
                                  grep -nr 'true' ./matches7.txt > m7run.txt
                                  while IFS= read -r line ; do
                                  DIR=$(echo $line | awk '{print $5}' )
                                  echo "$DIR"
                                  #docker build -f services/$DIR/build/Dockerfile .
                                  ls -l services/$DIR/build/
                                  done < m7run.txt
                                  else
                                  echo "not macth found"
                                  fi
                                   set -e     
                                '''	
                    
                        
                 
                }
            }    
            post{
                always{
                    cleanWs()
                }
            }   
        }     
    }
}
